# Generated by Django 3.0.8 on 2020-07-21 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Data',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='Deal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer', models.CharField(max_length=50, verbose_name='customer')),
                ('item', models.CharField(max_length=50, verbose_name='item')),
                ('total', models.IntegerField(verbose_name='total')),
                ('quantity', models.IntegerField(verbose_name='quantity')),
                ('date', models.DateField(verbose_name='date')),
                ('date1', models.DateField(null=True, verbose_name='date')),
            ],
        ),
    ]
