# Generated by Django 3.0.8 on 2020-07-21 06:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('deals', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='deal',
            name='date1',
        ),
    ]
