# Generated by Django 3.0.8 on 2020-07-21 09:15

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deals', '0002_remove_deal_date1'),
    ]

    operations = [
        migrations.CreateModel(
            name='ResultResponse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=50, verbose_name='username')),
                ('spent_money', models.IntegerField(verbose_name='spent_money')),
                ('gems', models.CharField(max_length=50, verbose_name='gems')),
            ],
        ),
        migrations.AlterField(
            model_name='data',
            name='file',
            field=models.FileField(upload_to='', validators=[django.core.validators.FileExtensionValidator(['csv'])]),
        ),
        migrations.AlterField(
            model_name='deal',
            name='date',
            field=models.DateTimeField(verbose_name='date'),
        ),
    ]
